name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
executables:
  showcase_server: server

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  json: ^0.20.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.8.0
  drift: ^2.26.0
  drift_postgres: ^1.3.0
  crypto: ^3.0.6
  http: ^1.2.2
  path: ^1.9.1
  convert: ^3.1.2
  collection: ^1.19.1
  args: ^2.6.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.13
